project_name: awsexec

builds:
  - id: awsexec
    main: ./cmd/awsexec
    binary: awsexec
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - '7'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    builds:
      - awsexec
    format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ .Ext }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
